// <auto-generated />
using System;
using BurakSekmen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BurakSekmen.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231123161318_mig_2")]
    partial class mig_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BurakSekmen.Models.AracKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AracKategoriAdi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VarChar");

                    b.HasKey("Id");

                    b.ToTable("AracKategoris");
                });

            modelBuilder.Entity("BurakSekmen.Models.AracYakıt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AracYakıtTuru")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VarChar");

                    b.HasKey("Id");

                    b.ToTable("AracYaks");
                });

            modelBuilder.Entity("BurakSekmen.Models.Siteseo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hakkimizda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siteanahtarkelime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sitebasligi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sitelogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Siteseos");
                });

            modelBuilder.Entity("BurakSekmen.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BurakSekmen.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AracAcıklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VarChar");

                    b.Property<string>("AracAdı")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VarChar");

                    b.Property<int>("AracKategorId")
                        .HasColumnType("int");

                    b.Property<string>("AracKoltukSayisi")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("VarChar");

                    b.Property<string>("AracMotorTip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VarChar");

                    b.Property<string>("AracValizSayisi")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("VarChar");

                    b.Property<string>("AracYakitTuruId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracYakıId")
                        .HasColumnType("int");

                    b.Property<string>("Arackm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VarChar");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AracKategorId");

                    b.HasIndex("AracYakıId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("BurakSekmen.Models.Vehicle", b =>
                {
                    b.HasOne("BurakSekmen.Models.AracKategori", "AracKategori")
                        .WithMany("vehicles")
                        .HasForeignKey("AracKategorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurakSekmen.Models.AracYakıt", "aracYakıt")
                        .WithMany("vehicles")
                        .HasForeignKey("AracYakıId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AracKategori");

                    b.Navigation("aracYakıt");
                });

            modelBuilder.Entity("BurakSekmen.Models.AracKategori", b =>
                {
                    b.Navigation("vehicles");
                });

            modelBuilder.Entity("BurakSekmen.Models.AracYakıt", b =>
                {
                    b.Navigation("vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
